structure(list(value = c("A", "NS", "MD", "MF", "CNAME", "SOA",
"MB", "MG", "MR", "NULL", "WKS", "PTR", "HINFO", "MINFO", "MX",
"TXT", "RP", "AFSDB", "X25", "ISDN", "RT", "NSAP", "NSAP-PTR",
"SIG", "KEY", "PX", "GPOS", "AAAA", "LOC", "NXT", "EID", "NIMLOC",
"SRV", "ATMA", "NAPTR", "KX", "CERT", "A6", "DNAME", "SINK",
"OPT", "APL", "DS", "SSHFP", "IPSECKEY", "RRSIG", "NSEC", "DNSKEY",
"DHCID", "NSEC3", "NSEC3PARAM", "TLSA", "SMIMEA", "Unassigned",
"HIP", "NINFO", "RKEY", "TALINK", "CDS", "CDNSKEY", "OPENPGPKEY",
"CSYNC", "Unassigned", "SPF", "UINFO", "UID", "GID", "UNSPEC",
"NID", "L32", "L64", "LP", "EUI48", "EUI64", "Unassigned", "TKEY",
"TSIG", "IXFR", "AXFR", "MAILB", "MAILA", "*", "URI", "CAA",
"AVC", "DOA", "Unassigned", "TA", "DLV", "Unassigned", "Private use",
"Reserved"), type = c("1", "2", "3", "4", "5", "6", "7", "8",
"9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
"20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30",
"31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41",
"42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52",
"53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63-98",
"99", "100", "101", "102", "103", "104", "105", "106", "107",
"108", "109", "110-248", "249", "250", "251", "252", "253", "254",
"255", "256", "257", "258", "259", "260-32767", "32768", "32769",
"32770-65279", "65280-65534", "65535"), meaning = c("a host address",
"an authoritative name server", "a mail destination (OBSOLETE - use MX)",
"a mail forwarder (OBSOLETE - use MX)", "the canonical name for an alias",
"marks the start of a zone of authority", "a mailbox domain name (EXPERIMENTAL)",
"a mail group member (EXPERIMENTAL)", "a mail rename domain name (EXPERIMENTAL)",
"a null RR (EXPERIMENTAL)", "a well known service description",
"a domain name pointer", "host information", "mailbox or mail list information",
"mail exchange", "text strings", "for Responsible Person", "for AFS Data Base location",
"for X.25 PSDN address", "for ISDN address", "for Route Through",
"for NSAP address, NSAP style A record", "for domain name pointer, NSAP style",
"for security signature", "for security key", "X.400 mail mapping information",
"Geographical Position", "IP6 Address", "Location Information",
"Next Domain (OBSOLETE)", "Endpoint Identifier", "Nimrod Locator",
"Server Selection", "ATM Address", "Naming Authority Pointer",
"Key Exchanger", "CERT", "A6 (OBSOLETE - use AAAA)", "DNAME",
"SINK", "OPT", "APL", "Delegation Signer", "SSH Key Fingerprint",
"IPSECKEY", "RRSIG", "NSEC", "DNSKEY", "DHCID", "NSEC3", "NSEC3PARAM",
"TLSA", "S/MIME cert association", NA, "Host Identity Protocol",
"NINFO", "RKEY", "Trust Anchor LINK", "Child DS", "DNSKEY(s) the Child wants reflected in DS",
"OpenPGP Key", "Child-To-Parent Synchronization", NA, NA, NA,
NA, NA, NA, NA, NA, NA, NA, "an EUI-48 address", "an EUI-64 address",
NA, "Transaction Key", "Transaction Signature", "incremental transfer",
"transfer of an entire zone", "mailbox-related RRs (MB, MG or MR)",
"mail agent RRs (OBSOLETE - see MX)", "A request for all records the server/cache has available",
"URI", "Certification Authority Restriction", "Application Visibility and Control",
"Digital Object Architecture", NA, "DNSSEC Trust Authorities",
"DNSSEC Lookaside Validation", NA, NA, NA)), .Names = c("value",
"type", "meaning"), row.names = c(NA, -92L), class = c("tbl_df",
"tbl", "data.frame")) -> .vdt